server:
  port: 8080
  servlet:
    context-path: /myblog
spring:
  application:
    name: community
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/community?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
  mail:
    host: smtp.163.com
    port: 465
    username: 18727504771@163.com
    password: 2411642zX
    protocol: smtps
    properties:
      mail:
        smtp:
          ssl:
            enable: true
#  redis:
#    host: 192.168.150.101
#    port: 6379
#    password: 123321
#    lettuce:
#      pool:
#        max-active: 10
#        max-idle: 10
#        min-idle: 1
#        time-between-eviction-runs: 10s
#  jackson:
#    default-property-inclusion: non_null # JSON处理时忽略非空字段
#mybatis-plus:
#  type-aliases-package: com.hmdp.entity # 别名扫描包
#logging:
#  level:
#    com.hmdp: debug
#  pattern:
#    dateformat: mm:ss.SSS